# -*- coding: utf-8 -*-
"""Data cleaning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qT4BW4JFzC_8Fdn77tGY9T2s0oq6XN6O
"""

import pandas as pd
from google.colab import files
import io

data_set = files.upload()

df = pd.read_csv(io.BytesIO(data_set["Superstore.csv"]), encoding = "unicode_escape")

df

df.dropna(how = 'all' , inplace = True)

df

df['Country'].replace({'USA':'United States'}, inplace = True )

df['Country'].unique()

mean = df['Sales'].mean()

df['Sales'].fillna(value = 'mean' , inplace = True)

df

df.to_csv('Data cleaning.csv')

files.download("Data cleaning.csv")

